In [1]:
import os
import re
import requests
import pandas as pd
import matplotlib.pyplot as plt
from datetime import datetime, timedelta, timezone
import xml.etree.ElementTree as ET
import time
from pathlib import Path

PROJECT_ROOT = Path(r"G:/Final_proj/Total_clear/데이터")
EDA_OUTPUT_DIR = PROJECT_ROOT / "1.EDA_outputs"
EDA_OUTPUT_DIR.mkdir(exist_ok=True)

print(f"저장 경로: {EDA_OUTPUT_DIR}")

In [11]:
# 호출할 API URL 입력
url = 'http://apis.data.go.kr/1471000/FtnltCosmRptPrdlstInfoService/getRptPrdlstInq'

dfs = []
page = 1

while True:
    params = {
        'serviceKey': '7e22cdfd1f3b7c77ca6c3dbfda2a2735146d86adbe40aaf01a500b09801c1d92',
        'pageNo': page,
        'numOfRows': 500,
        'type': 'json'
    }

    r = requests.get(url, params=params)
    data = r.json()

    items = data.get('body', {}).get('items', [])
    if not items:
        break

    dfs.append(pd.DataFrame(items))
    print(f"{page}페이지 수집 완료")

    page += 1
    time.sleep(0.2)

final_df = pd.concat(dfs, ignore_index=True)
print(final_df.shape)

1페이지 수집 완료
2페이지 수집 완료
3페이지 수집 완료
4페이지 수집 완료
5페이지 수집 완료
6페이지 수집 완료
7페이지 수집 완료
8페이지 수집 완료
9페이지 수집 완료
10페이지 수집 완료
11페이지 수집 완료
12페이지 수집 완료
13페이지 수집 완료
14페이지 수집 완료
15페이지 수집 완료
16페이지 수집 완료
17페이지 수집 완료
18페이지 수집 완료
19페이지 수집 완료
20페이지 수집 완료
21페이지 수집 완료
22페이지 수집 완료
23페이지 수집 완료
24페이지 수집 완료
25페이지 수집 완료
26페이지 수집 완료
27페이지 수집 완료
28페이지 수집 완료
29페이지 수집 완료
30페이지 수집 완료
31페이지 수집 완료
32페이지 수집 완료
33페이지 수집 완료
34페이지 수집 완료
35페이지 수집 완료
36페이지 수집 완료
37페이지 수집 완료
38페이지 수집 완료
39페이지 수집 완료
40페이지 수집 완료
41페이지 수집 완료
42페이지 수집 완료
43페이지 수집 완료
44페이지 수집 완료
45페이지 수집 완료
46페이지 수집 완료
47페이지 수집 완료
48페이지 수집 완료
49페이지 수집 완료
50페이지 수집 완료
51페이지 수집 완료
52페이지 수집 완료
53페이지 수집 완료
54페이지 수집 완료
55페이지 수집 완료
56페이지 수집 완료
57페이지 수집 완료
58페이지 수집 완료
59페이지 수집 완료
60페이지 수집 완료
61페이지 수집 완료
62페이지 수집 완료
63페이지 수집 완료
64페이지 수집 완료
65페이지 수집 완료
66페이지 수집 완료
67페이지 수집 완료
68페이지 수집 완료
69페이지 수집 완료
70페이지 수집 완료
71페이지 수집 완료
72페이지 수집 완료
73페이지 수집 완료
74페이지 수집 완료
75페이지 수집 완료
76페이지 수집 완료
77페이지 수집 완료
78페이지 수집 완료
79페이지 수집 완료
80페이지 수집 완료
81페이지 수집 완료
82페이지 수집 완료
83페이지 수집 완료
84페이지 수집 완료
85페이지 수집 완료
86페이지 수집 완료
87페이지 수집 완료
88페이지 수집 완료
89페이지 수집 완료
90페이지 수집 완료
91페이지 수집 완료
92페이지 수집 완료
93페이지 수집 완료
94페이지 수집 완료
95페이지 수집 완료
96페이지 수집 완료
97페이지 수집 완료
98페이지 수집 완료
99페이지 수집 완료
100페이지 수집 완료
101페이지 수집 완료
102페이지 수집 완료
103페이지 수집 완료
104페이지 수집 완료
105페이지 수집 완료
106페이지 수집 완료
107페이지 수집 완료
108페이지 수집 완료
109페이지 수집 완료
110페이지 수집 완료
111페이지 수집 완료
112페이지 수집 완료
113페이지 수집 완료
114페이지 수집 완료
115페이지 수집 완료
116페이지 수집 완료
117페이지 수집 완료
118페이지 수집 완료
119페이지 수집 완료
120페이지 수집 완료
121페이지 수집 완료
122페이지 수집 완료
123페이지 수집 완료
124페이지 수집 완료
125페이지 수집 완료
126페이지 수집 완료
127페이지 수집 완료
128페이지 수집 완료
129페이지 수집 완료
130페이지 수집 완료
131페이지 수집 완료
132페이지 수집 완료
133페이지 수집 완료
134페이지 수집 완료
135페이지 수집 완료
136페이지 수집 완료
137페이지 수집 완료
138페이지 수집 완료
139페이지 수집 완료
140페이지 수집 완료
141페이지 수집 완료
142페이지 수집 완료
143페이지 수집 완료
144페이지 수집 완료
145페이지 수집 완료
146페이지 수집 완료
147페이지 수집 완료
148페이지 수집 완료
149페이지 수집 완료
150페이지 수집 완료
151페이지 수집 완료
152페이지 수집 완료
153페이지 수집 완료
154페이지 수집 완료
155페이지 수집 완료
156페이지 수집 완료
157페이지 수집 완료
158페이지 수집 완료
159페이지 수집 완료
160페이지 수집 완료
161페이지 수집 완료
162페이지 수집 완료
163페이지 수집 완료
164페이지 수집 완료
165페이지 수집 완료
166페이지 수집 완료
167페이지 수집 완료
168페이지 수집 완료
169페이지 수집 완료
170페이지 수집 완료
171페이지 수집 완료
172페이지 수집 완료
173페이지 수집 완료
174페이지 수집 완료
175페이지 수집 완료
176페이지 수집 완료
177페이지 수집 완료
178페이지 수집 완료
179페이지 수집 완료
180페이지 수집 완료
181페이지 수집 완료
182페이지 수집 완료
183페이지 수집 완료
184페이지 수집 완료
185페이지 수집 완료
186페이지 수집 완료
187페이지 수집 완료
188페이지 수집 완료
189페이지 수집 완료
190페이지 수집 완료
191페이지 수집 완료
192페이지 수집 완료
193페이지 수집 완료
194페이지 수집 완료
195페이지 수집 완료
196페이지 수집 완료
197페이지 수집 완료
198페이지 수집 완료
199페이지 수집 완료
200페이지 수집 완료
201페이지 수집 완료
202페이지 수집 완료
203페이지 수집 완료
204페이지 수집 완료
205페이지 수집 완료
206페이지 수집 완료
207페이지 수집 완료
208페이지 수집 완료
209페이지 수집 완료
210페이지 수집 완료
211페이지 수집 완료
212페이지 수집 완료
213페이지 수집 완료
214페이지 수집 완료
215페이지 수집 완료
216페이지 수집 완료
217페이지 수집 완료
218페이지 수집 완료
219페이지 수집 완료
220페이지 수집 완료
221페이지 수집 완료
222페이지 수집 완료
223페이지 수집 완료
224페이지 수집 완료
225페이지 수집 완료
226페이지 수집 완료
227페이지 수집 완료
228페이지 수집 완료
229페이지 수집 완료
230페이지 수집 완료
231페이지 수집 완료
232페이지 수집 완료
233페이지 수집 완료
234페이지 수집 완료
235페이지 수집 완료
236페이지 수집 완료
237페이지 수집 완료
238페이지 수집 완료
239페이지 수집 완료
240페이지 수집 완료
241페이지 수집 완료
242페이지 수집 완료
243페이지 수집 완료
244페이지 수집 완료
245페이지 수집 완료
246페이지 수집 완료
247페이지 수집 완료
248페이지 수집 완료
249페이지 수집 완료
250페이지 수집 완료
251페이지 수집 완료
252페이지 수집 완료
253페이지 수집 완료
254페이지 수집 완료
255페이지 수집 완료
256페이지 수집 완료
257페이지 수집 완료
258페이지 수집 완료
259페이지 수집 완료
260페이지 수집 완료
261페이지 수집 완료
262페이지 수집 완료
263페이지 수집 완료
264페이지 수집 완료
265페이지 수집 완료
266페이지 수집 완료
267페이지 수집 완료
268페이지 수집 완료
269페이지 수집 완료
270페이지 수집 완료
271페이지 수집 완료
272페이지 수집 완료
273페이지 수집 완료
274페이지 수집 완료
275페이지 수집 완료
276페이지 수집 완료
277페이지 수집 완료
278페이지 수집 완료
279페이지 수집 완료
280페이지 수집 완료
281페이지 수집 완료
282페이지 수집 완료
283페이지 수집 완료
284페이지 수집 완료
285페이지 수집 완료
286페이지 수집 완료
287페이지 수집 완료
288페이지 수집 완료
289페이지 수집 완료
290페이지 수집 완료
291페이지 수집 완료
292페이지 수집 완료
293페이지 수집 완료
294페이지 수집 완료
295페이지 수집 완료
296페이지 수집 완료
297페이지 수집 완료
298페이지 수집 완료
299페이지 수집 완료
300페이지 수집 완료
301페이지 수집 완료
302페이지 수집 완료
303페이지 수집 완료
304페이지 수집 완료
305페이지 수집 완료
306페이지 수집 완료
307페이지 수집 완료
308페이지 수집 완료
309페이지 수집 완료
310페이지 수집 완료
311페이지 수집 완료
312페이지 수집 완료
313페이지 수집 완료
314페이지 수집 완료
315페이지 수집 완료
316페이지 수집 완료
317페이지 수집 완료
318페이지 수집 완료
319페이지 수집 완료
320페이지 수집 완료
321페이지 수집 완료
322페이지 수집 완료
323페이지 수집 완료
324페이지 수집 완료
325페이지 수집 완료
326페이지 수집 완료
327페이지 수집 완료
328페이지 수집 완료
329페이지 수집 완료
330페이지 수집 완료
331페이지 수집 완료
332페이지 수집 완료
333페이지 수집 완료
334페이지 수집 완료
335페이지 수집 완료
336페이지 수집 완료
337페이지 수집 완료
338페이지 수집 완료
339페이지 수집 완료
340페이지 수집 완료
341페이지 수집 완료
342페이지 수집 완료
343페이지 수집 완료
344페이지 수집 완료
345페이지 수집 완료
346페이지 수집 완료
347페이지 수집 완료
348페이지 수집 완료
349페이지 수집 완료
350페이지 수집 완료
351페이지 수집 완료
352페이지 수집 완료
353페이지 수집 완료
354페이지 수집 완료
355페이지 수집 완료
356페이지 수집 완료
357페이지 수집 완료
358페이지 수집 완료
359페이지 수집 완료
360페이지 수집 완료
361페이지 수집 완료
362페이지 수집 완료
363페이지 수집 완료
364페이지 수집 완료
365페이지 수집 완료
366페이지 수집 완료
367페이지 수집 완료
368페이지 수집 완료
369페이지 수집 완료
370페이지 수집 완료
371페이지 수집 완료
(185190, 36)

In [12]:
final_df

,COSMETIC_REPORT_SEQ,ITEM_SEQ,ITEM_NAME,DEPT_RECEIPT_NO,REPORT_FLAG_CODE,REPORT_FLAG_NAME,MANUF_NAME,MANUF_COUNTRY_CODE,MANUF_COUNTRY_NAME,MANUF_PLACE,...,USAGE_DOSAGE,EFFECT_YN1,EFFECT_YN2,EFFECT_YN3,WATER_PROOFING_FLAG,WATER_PROOFING_NAME,EE_DOC_DATA,UD_DOC_DATA,NB_DOC_DATA,BIZRNO
0,2008000083,NaN,더마바이탈나노펩타이드토너,200800109034,A,제조,NaN,NaN,NaN,NaN,...,None,N,N,N,None,,None,None,None,3078118303
1,2008000112,NaN,더마바이탈나노펩타이드에멀젼,200800109843,A,제조,NaN,NaN,NaN,NaN,...,None,N,N,N,None,,None,None,None,3078118303
2,2008000113,NaN,더마바이탈나노펩타이드세럼,200800109845,A,제조,NaN,NaN,NaN,NaN,...,None,N,N,N,None,,None,None,None,3078118303
3,2008000114,NaN,더마바이탈나노펩타이드크림,200800109847,A,제조,NaN,NaN,NaN,NaN,...,None,N,N,N,None,,None,None,None,3078118303
4,2008000118,NaN,레비스페이셜펩타이드크림,200800109884,F,수입,엠디유에스에이,US,미국,캘리포니아 산타페스프링스 이스트파이어,...,None,N,N,N,None,,None,None,None,1298622949
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
185185,2026003941,202402108,셀로맥스포시즌스톤업비비,202600179460,A,제조,None,None,None,None,...,본품 적당량을 취해 피부에 골고루 펴 바른다.,N,N,N,0,,"<DOC title=""효능효과"" type=""EE"">\r\n <SECTION tit...","<DOC title=""용법용량"" type=""UD"">\r\n <SECTION tit...","<DOC title=""사용할 때의 주의사항"" type=""NB"">\r\n <SECT...",1258627262
185186,2026003942,202301081,울트라라이트데일리선스크린,202600179576,A,제조,None,None,None,None,...,본품 적당량을 취해 피부에 골고루 펴 바른다.,NaN,NaN,NaN,0,,"<DOC title=""효능효과"" type=""EE"">\r\n <SECTION tit...","<DOC title=""용법용량"" type=""UD"">\r\n <SECTION tit...","<DOC title=""사용할 때의 주의사항"" type=""NB"">\r\n <SECT...",1088616488
185187,2026003943,202203796,피쓰판테티놀선에센스,202600179779,A,제조,None,None,None,None,...,본 품 적당량을 취하여 피부에 골고루 펴 바른다.\n,NaN,NaN,NaN,0,,"<DOC title=""효능효과"" type=""EE"">\r\n <SECTION tit...","<DOC title=""용법용량"" type=""UD"">\r\n <SECTION tit...","<DOC title=""사용할 때의 주의사항"" type=""NB"">\r\n <SECT...",5728802699
185188,2026003944,NaN,픽셀퓨어슬로우에이징크림랩핑마스크시트,202600179818,A,제조,None,None,None,None,...,본품을 피부에 붙이고 10~20분 후 지지체를 제거한 다음 남은 제품을 골고루 펴 ...,NaN,NaN,NaN,NaN,,NaN,NaN,NaN,1118438733
185189,2026003945,201903841,베몽테스악신부스터솔라비드,202600179835,A,제조,None,None,None,None,...,본 품을 적당량을 취해 피부에 고루 펴 바른다.\n,N,N,N,0,,"<DOC title=""효능효과"" type=""EE"">\r\n <SECTION tit...","<DOC title=""용법용량"" type=""UD"">\r\n <SECTION tit...","<DOC title=""사용상의주의사항"" type=""NB"">\r\n <SECTION...",7398101940

In [13]:
final_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 185190 entries, 0 to 185189
Data columns (total 36 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   COSMETIC_REPORT_SEQ        185190 non-null  str
 1   ITEM_SEQ                   65491 non-null   str
 2   ITEM_NAME                  185190 non-null  str
 3   DEPT_RECEIPT_NO            185190 non-null  str
 4   REPORT_FLAG_CODE           185190 non-null  str
 5   REPORT_FLAG_NAME           185190 non-null  str
 6   MANUF_NAME                 75 non-null      object
 7   MANUF_COUNTRY_CODE         104 non-null     object
 8   MANUF_COUNTRY_NAME         104 non-null     object
 9   MANUF_PLACE                74 non-null      object
 10  ITEM_PH                    185126 non-null  str
 11  COSMETIC_TARGET_FLAG       185190 non-null  str
 12  COSMETIC_TARGET_FLAG_NAME  185190 non-null  str
 13  COSMETIC_STD_CODE          31413 non-null   object
 14  COSMETIC_STD_NAME          31413 non-null   object
 15  ENTP_NAME                  185190 non-null  str
 16  ENTP_SEQ                   185190 non-null  str
 17  REPORT_DATE                185190 non-null  str
 18  CANCEL_REQ_DATE            116 non-null     object
 19  CANCEL_APPROVAL_DATE       1 non-null       object
 20  CANCEL_APPROVAL_YN         185190 non-null  str
 21  ETHANOL_OVER_YN            35886 non-null   object
 22  EE_CODE                    110438 non-null  object
 23  EE_NAME                    110438 non-null  object
 24  SPF                        39189 non-null   object
 25  PA                         39198 non-null   object
 26  USAGE_DOSAGE               170027 non-null  object
 27  EFFECT_YN1                 122261 non-null  str
 28  EFFECT_YN2                 122255 non-null  str
 29  EFFECT_YN3                 122272 non-null  str
 30  WATER_PROOFING_FLAG        39205 non-null   object
 31  WATER_PROOFING_NAME        185190 non-null  str
 32  EE_DOC_DATA                63996 non-null   object
 33  UD_DOC_DATA                64002 non-null   object
 34  NB_DOC_DATA                64116 non-null   object
 35  BIZRNO                     185188 non-null  str
dtypes: object(18), str(18)
memory usage: 79.1+ MB

In [14]:
final_df['ITEM_NAME'] = final_df['ITEM_NAME'].str.strip()
final_df['ITEM_NAME'] = final_df['ITEM_NAME'].str.replace(' ', '', regex=False)

In [15]:
final_df.to_csv(EDA_OUTPUT_DIR / "functional_cosmetics.csv", index=False, encoding="utf-8-sig")
print(f"저장 완료: {EDA_OUTPUT_DIR / 'functional_cosmetics.csv'}")

In [2]:
# 호출할 API URL 입력
url = 'http://apis.data.go.kr/1471000/FtnltCosmRptPrdlstInfoService/getRptEntpInq'

dfs = []
page = 1

while True:
    params = {
        'serviceKey': '7e22cdfd1f3b7c77ca6c3dbfda2a2735146d86adbe40aaf01a500b09801c1d92',
        'pageNo': page,
        'numOfRows': 500,
        'type': 'json'
    }

    r = requests.get(url, params=params)
    data = r.json()

    items = data.get('body', {}).get('items', [])
    if not items:
        break

    dfs.append(pd.DataFrame(items))
    print(f"{page}페이지 수집 완료")

    page += 1
    time.sleep(0.2)

company = pd.concat(dfs, ignore_index=True)
print(company.shape)

1페이지 수집 완료
2페이지 수집 완료
3페이지 수집 완료
4페이지 수집 완료
5페이지 수집 완료
6페이지 수집 완료
7페이지 수집 완료
8페이지 수집 완료
9페이지 수집 완료
10페이지 수집 완료
11페이지 수집 완료
12페이지 수집 완료
13페이지 수집 완료
14페이지 수집 완료
15페이지 수집 완료
16페이지 수집 완료
17페이지 수집 완료
18페이지 수집 완료
19페이지 수집 완료
20페이지 수집 완료
21페이지 수집 완료
22페이지 수집 완료
23페이지 수집 완료
24페이지 수집 완료
25페이지 수집 완료
26페이지 수집 완료
27페이지 수집 완료
28페이지 수집 완료
29페이지 수집 완료
30페이지 수집 완료
31페이지 수집 완료
32페이지 수집 완료
33페이지 수집 완료
34페이지 수집 완료
35페이지 수집 완료
36페이지 수집 완료
37페이지 수집 완료
38페이지 수집 완료
39페이지 수집 완료
40페이지 수집 완료
41페이지 수집 완료
42페이지 수집 완료
43페이지 수집 완료
44페이지 수집 완료
45페이지 수집 완료
46페이지 수집 완료
47페이지 수집 완료
48페이지 수집 완료
49페이지 수집 완료
50페이지 수집 완료
51페이지 수집 완료
52페이지 수집 완료
53페이지 수집 완료
54페이지 수집 완료
55페이지 수집 완료
56페이지 수집 완료
57페이지 수집 완료
58페이지 수집 완료
59페이지 수집 완료
60페이지 수집 완료
61페이지 수집 완료
62페이지 수집 완료
63페이지 수집 완료
64페이지 수집 완료
65페이지 수집 완료
66페이지 수집 완료
67페이지 수집 완료
68페이지 수집 완료
69페이지 수집 완료
70페이지 수집 완료
71페이지 수집 완료
72페이지 수집 완료
73페이지 수집 완료
74페이지 수집 완료
75페이지 수집 완료
76페이지 수집 완료
77페이지 수집 완료
78페이지 수집 완료
79페이지 수집 완료
80페이지 수집 완료
(39718, 13)

In [3]:
company

,ENTP_SEQ,ENTP_NAME,COB_CODE,COB_NAME,ENTP_NO,PERMIT_KIND_CODE,PERMIT_KIND_NAME,KFDA_PERMIT_CODE,KFDA_PERMIT_NAME,BOSS_NAME,FACTORY_ADDR,ENTP_PERMIT_DATE,BIZRNO
0,19320001,(주)보령,B,의약외품,0454,A,허가,30000,경인청,김정균,경기도 안산시 단원구 능안로 107,19791025,2088100281
1,19540001,동아에스티(주),A,의약품,1290,A,허가,60000,대전청,정재훈,"충청남도 천안시 서북구 백석공단1로 200-23 (2B, 3, 4B층)",19541213,2048640122
2,19540005,삼성제약(주),A,의약품,1294,A,허가,00000,식약처,정성택,경기도 화성시 향남읍 제약공단4길 10,19541230,2078100726
3,19540006,일동제약(주),A,의약품,1293,A,허가,60000,대전청,윤폴웅섭(윤웅섭),경기도 안성시 공단1로 25,19541231,6828500435
4,19540006,일동제약(주),A,의약품,1293,A,허가,60000,대전청,이재준,경기도 안성시 공단1로 25,19541231,6828500435
...,...,...,...,...,...,...,...,...,...,...,...,...,...
39713,2026001184,(주)신우코퍼레이션,W,화장품책임판매,52711,NaN,NaN,30000,경인청,신준수,경기도 오산시 독산성로 425 5층 506호,20260204,6968103049
39714,2026001185,주식회사 커즈코스메틱,W,화장품책임판매,52712,NaN,NaN,20000,부산청,권재민,"부산광역시 북구 금곡대로303번길 35 , 702-164호",20260204,5388803325
39715,2026001186,주식회사 가비진,V,화장품제조,7606,NaN,NaN,20000,부산청,김현진,"부산광역시 강서구 가리새1로25번길 6 , 2층",20260204,5598103717
39716,2026001187,주식회사 가비진,W,화장품책임판매,52713,NaN,NaN,20000,부산청,김현진,"부산광역시 강서구 가리새1로25번길 6 , 2층",20260204,5598103717
39717,99990013,주식회사 에이징,D,화장품,6,A,허가,40000,대구청,최성곤,대구광역시 달서구 성서공단로50길 21,20031204,5140983008

In [4]:
company.to_csv(EDA_OUTPUT_DIR / "functional_cosmetic_company.csv", index=False, encoding="utf-8-sig")
print(f"저장 완료: {EDA_OUTPUT_DIR / 'functional_cosmetic_company.csv'}")